---
title: 如何自定义 Exception Filter
date: 2025-03-10 14:24:01
permalink: /pages/nestexceptionfilter/
categories:
  - 服务端
  - Nest
tags:
  - 
author: 
  name: 神说要有光
  link: https://juejin.cn/book/7226988578700525605?scrollMenuIndex=1
titleTag: 
---
## Exception Filter

Exception Filter 是在 Nest 应用抛异常的时候，捕获它并返回一个对应的响应。

比如路由找不到时返回 404：

![](https://s2.loli.net/2025/03/27/KaDuMB1C9NlL2Po.png)

服务端报错时返回 500：

![](https://s2.loli.net/2025/03/27/nhjcv5uYsFzxNDX.png)

参数的错误返回 400：

![](https://s2.loli.net/2025/03/27/hj9UA6agoVwXZBI.png)

这些都是 Exception Filter 做的事情。

那么，如果我们想自定义异常时返回的响应格式呢？

这种就要自定义 Exception Filter 了。

创建个 nest 项目：

```
nest new exception-filter-test
```
![](https://s2.loli.net/2025/03/27/F5TIV7aHdRv3G46.png)

把它跑起来：

```
npm run start:dev
```

![](https://s2.loli.net/2025/03/27/SLU64vrQb7oPetC.png)

浏览器访问 http://localhost:3000 可以看到 hello world，代表服务跑起来了：

![](https://s2.loli.net/2025/03/27/CYosm6Bab7yXONE.png)

然后在 controller 里抛个异常： 

![](https://s2.loli.net/2025/03/27/ap3ij5EZBP2zWbw.png)

```javascript
throw new HttpException('xxxx', HttpStatus.BAD_REQUEST)
```
这个 HttpStatus 就是一些状态码的常量：

![](https://s2.loli.net/2025/03/27/eFc7yEzWKOT3Cf6.gif)

这时候刷新页面，返回的就是 400 对应的响应：

![](https://s2.loli.net/2025/03/27/jbPuoOTeCYFrlvW.png)

这个响应的格式是内置的 Exception Filter 生成的。

当然，你也可以直接抛具体的异常：

![](https://s2.loli.net/2025/03/27/ybTEDshvtLI7NKM.png)

![](https://s2.loli.net/2025/03/27/31U5GMnYPkciab7.png)

## 自定义 Exception Filter

然后我们自己定义个 exception filter：

```
nest g filter hello --flat --no-spec
```

--flat 是不生成 hello 目录，--no-spec 是不生成测试文件。

![](https://s2.loli.net/2025/03/27/1fROkwl5YCn7HgN.png)

![](https://s2.loli.net/2025/03/27/iqwGcHp1RI7UvWL.png)

@Catch 指定要捕获的异常，这里指定 BadRequestException。


```javascript
import { ArgumentsHost, BadRequestException, Catch, ExceptionFilter } from '@nestjs/common';

@Catch(BadRequestException)
export class HelloFilter implements ExceptionFilter {
  catch(exception: BadRequestException, host: ArgumentsHost) {
    debugger;
  }
}
```
先打个断点。

### 全局引用

在 AppModule 里引入：

![](https://s2.loli.net/2025/03/27/STLDiZy49FJACUb.png)

```javascript
app.useGlobalFilters(new HelloFilter());
```
### 局部启用

如果你想局部启用，可以加在 handler 或者 controller 上：

![](https://s2.loli.net/2025/03/27/4vHdA9rZbsMoP1T.png)

![](https://s2.loli.net/2025/03/27/IoXAcNEManuL7bU.png)

然后新建个调试配置文件：

![](https://s2.loli.net/2025/03/27/DShVdXkMPji3Ocb.png)

输入调试配置：

![](https://s2.loli.net/2025/03/27/wh3Zov57HGMzW6O.png)

```json
{
    "type": "node",
    "request": "launch",
    "name": "debug nest",
    "runtimeExecutable": "npm",
    "args": [
        "run",
        "start:dev",
    ],
    "skipFiles": [
        "<node_internals>/**"
    ],
    "console": "integratedTerminal",
}
```
把之前的服务关掉，点击调试启动：

![](https://s2.loli.net/2025/03/27/COGrxv1o5spP698.png)

刷新页面，代码会在断点处断住：

![](https://s2.loli.net/2025/03/27/hjzyOIscRST74lP.png)

我们只要根据异常信息返回对应的响应就可以了：

![](https://s2.loli.net/2025/03/27/7ozGQkugtTB4ePH.png)

```javascript
import { ArgumentsHost, BadRequestException, Catch, ExceptionFilter, HttpException } from '@nestjs/common';
import { Response } from 'express';

@Catch(BadRequestException)
export class HelloFilter implements ExceptionFilter {
  catch(exception: BadRequestException, host: ArgumentsHost) {
    const http = host.switchToHttp();
    const response = http.getResponse<Response>();

    const statusCode = exception.getStatus();

    response.status(statusCode).json({
       code: statusCode,
       message: exception.message,
       error: 'Bad Request',
       xxx: 111
    })
  }
}

```
这样，抛异常时返回的响应就是自定义的了：

![](https://s2.loli.net/2025/03/27/CjLiNRGU12lFEsu.png)

但我们只是 @Catch 了 BadRequestException

如果抛的是其他异常，依然是原来的格式：

![](https://s2.loli.net/2025/03/27/kPMZGrgUaSO9Qzt.png)

比如我抛一个 BadGatewayException。

![](https://s2.loli.net/2025/03/27/gCRvLsVaDQIF4Yz.png)

依然是默认格式。

### 捕捉所有错误类型

那我们只要 @Catch 指定 HttpException 不就行了？

因为 BadRequestExeption、BadGateWayException 等都是它的子类。

![](https://s2.loli.net/2025/03/27/AXI6p9cTdzwxJfB.png)

试一下：

![](https://s2.loli.net/2025/03/27/hgznj6WDcLuKGJN.png)

![](https://s2.loli.net/2025/03/27/rm1Hfb43zxMotLh.png)

确实，现在所有的 HttpException 都会被处理了。

但其实这也有个问题。

就是当我们用了 ValidationPipe 的时候。

比如我们加一个路由：

```javascript
@Post('aaa') 
aaa(@Body() aaaDto: AaaDto ){
    return 'success';
}
```
然后创建 src/aaa.dto.ts

```javascript
export class AaaDto {
    aaa: string;
    
    bbb: number;
}
```
安装用到的包：

```
npm install --save class-validator class-transformer
```
然后给 AaaDto 添加几个校验规则：

```javascript
import { IsEmail, IsNotEmpty, IsNumber } from "class-validator";

export class AaaDto {
    @IsNotEmpty({message: 'aaa 不能为空'})
    @IsEmail({}, {message: 'aaa 不是邮箱格式'})
    aaa: string;
    
    @IsNumber({}, {message: 'bbb 不是数字'})
    @IsNotEmpty({message: 'bbb 不能为空'})
    bbb: number;
}
```
在 main.ts 启用 ValidationPipe：

![](https://s2.loli.net/2025/03/27/hUlTft4Jj9KSsIW.png)

```javascript
app.useGlobalPipes(new ValidationPipe());
```

在 postman 里测试下：

![](https://s2.loli.net/2025/03/27/z6P2wLpeIHZimjS.png)

可以看到，提示的错误也不对了。

因为我们自定义的 exception filter 会拦截所有 HttpException，但是没有对这种情况做支持。

![](https://s2.loli.net/2025/03/27/WUiOftZNjL7vG4e.png)

先不加这个 filter。

这时候响应是这样的：

![](https://s2.loli.net/2025/03/27/MJ7Y8wqWlbCu9Xi.png)

我们对这种情况做下支持：

![](https://s2.loli.net/2025/03/27/cbSWdTJs23zDjni.png)

启用自定义的 filter，然后打个断点：

![](https://s2.loli.net/2025/03/27/gKpdrVyAJfm56ek.png)

再次访问会在断点处断住：

![](https://s2.loli.net/2025/03/27/DZ691noc8RghAsU.png)

可以看到 ValidationPipe 的 response 格式是这样的。

所以我们可以这样改：

![](https://s2.loli.net/2025/03/27/cOzyvLoFGDgB3jU.png)

```javascript
import { ArgumentsHost, BadRequestException, Catch, ExceptionFilter, HttpException } from '@nestjs/common';
import { Response } from 'express';

@Catch(HttpException)
export class HelloFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const http = host.switchToHttp();
    const response = http.getResponse<Response>();

    const statusCode = exception.getStatus();

    const res = exception.getResponse() as { message: string[] };
    
    response.status(statusCode).json({
       code: statusCode,
       message: res?.message?.join ? res?.message?.join(',') : exception.message,
       error: 'Bad Request',
       xxx: 111
    })
  }
}
```

如果 response.message 是个数组，就返回 join 的结果，否则还是返回 exception.message

再试下：

![](https://s2.loli.net/2025/03/27/wHtE43KNxuyjar9.png)

![](https://s2.loli.net/2025/03/27/PFT4fIMRQXDnl9r.png)

现在，ValidationPipe 的错误和其他的错误就都返回了正确的格式。

### 在 Filter 里注入 AppService

那如果我想在 Filter 里注入 AppService 呢？

这就需要改一下注册方式：

![](https://s2.loli.net/2025/03/27/VOMXr7e8gtdzWlq.png)

不用 useGlobalFilters 注册了，而是在 AppModule 里注册一个 token 为 APP_FILTER 的 provider：

![](https://s2.loli.net/2025/03/27/deGFqutPkjJSrZO.png)

```javascript
{
  provide: APP_FILTER,
  useClass: HelloFilter
}
```
Nest 会把所有 token 为 APP_FILTER 的 provider 注册为全局 Exception Filter。

注册多个 Filter 也是这么写。

其余的全局 Guard、Interceptor、Pipe 也是这样注册：

![](https://s2.loli.net/2025/03/27/hB2RWZ6uHaVtcJL.png)

这样注册的好处就是可以注入其他 provider 了：

比如我注入了 AppService，然后调用它的 getHello 方法：

![](https://s2.loli.net/2025/03/27/r9Y4V85eC7Xa1AM.png)

```javascript
import { ArgumentsHost, BadRequestException, Catch, ExceptionFilter, HttpException, Inject } from '@nestjs/common';
import { Response } from 'express';
import { AppService } from './app.service';

@Catch(HttpException)
export class HelloFilter implements ExceptionFilter {

  @Inject(AppService)
  private service: AppService;

  catch(exception: HttpException, host: ArgumentsHost) {
    const http = host.switchToHttp();
    const response = http.getResponse<Response>();

    const statusCode = exception.getStatus();

    const res = exception.getResponse() as { message: string[] };
    
    response.status(statusCode).json({
       code: statusCode,
       message: res?.message?.join ? res?.message?.join(',') : exception.message,
       error: 'Bad Request',
       xxx: 111,
       yyy: this.service.getHello()
    })
  }
}
```
可以看到，service 方法调用成功了：

![](https://s2.loli.net/2025/03/27/2azBDOrVwLQqTtA.png)

### 自定义 Exception 

此外，如果你想自定义 Exception 也是可以的。

比如添加一个 src/unlogin.filter.ts 

```javascript
import { ArgumentsHost, Catch, ExceptionFilter, HttpStatus } from '@nestjs/common';
import { Response } from 'express';

export class UnLoginException{
  message: string;

  constructor(message?){
    this.message = message;
  }
}

@Catch(UnLoginException)
export class UnloginFilter implements ExceptionFilter {
  catch(exception: UnLoginException, host: ArgumentsHost) {
    const response = host.switchToHttp().getResponse<Response>();

    response.status(HttpStatus.UNAUTHORIZED).json({
      code: HttpStatus.UNAUTHORIZED,
      message: 'fail',
      data: exception.message || '用户未登录'
    }).end();
  }
}
```
我们创建了一个 UnloginException 的异常。

然后在 ExceptionFilter 里 @Catch 了它。

在 AppModule 里注册这个全局 Filter：

![](https://s2.loli.net/2025/03/27/8gEMaV1A4yJYmhj.png)

```javascript
{
  provide: APP_FILTER,
  useClass: UnloginFilter
}
```
之后在 AppController 里抛出这个异常：

![](https://s2.loli.net/2025/03/27/UPFoKpWXs2BuQ53.png)

浏览器里访问下：

![](https://s2.loli.net/2025/03/27/iISAVZs3ELwl4P1.png)

可以看到，返回的是我们自定义的格式。

也就是说，可以用自定义 Exception Filter 捕获内置的或者自定义的 Exception。

案例代码在[小册仓库](https://github.com/QuarkGluonPlasma/nestjs-course-code/tree/main/exception-filter-test)。
## 总结

这节我们学习了自定义 Exception Filter。

通过 @Catch 指定要捕获的异常，然后在 catch 方法里拿到异常信息，返回对应的响应。

如果捕获的是 HttpException，要注意兼容下 ValidationPipe 的错误格式的处理。

filter 可以通过 @UseFilters 加在 handler 或者 controller 上，也可以在 main.ts 用 app.useGlobalFilters 全局启用。

如果 filter 要注入其他 provider，就要通过 AppModule 里注册一个 token 为 APP_FILTER 的 provider 的方式。

此外，捕获的 Exception 也是可以自定义的。

这样，我们就可以自定义异常和异常返回的响应格式了。